FROM docker.io/library/golang:1.24-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    xvfb xdotool \
    gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-x gstreamer1.0-libav gstreamer1.0-tools \
    libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
    pulseaudio pulseaudio-utils \
    xfce4 xfce4-terminal \
    dbus dbus-x11 \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/pulse /run/pulse && \
    echo "autospawn = yes" > /etc/pulse/client.conf

WORKDIR /app

EXPOSE 8080
EXPOSE 50000-50100/udp
